services:
    mongodb-v4-prov:
        image: mongo:latest
        container_name: mongodb-v4-prov
        restart: always
        volumes:
            - ./provisioning/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27018:27017
    lyre-v4-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8443:8443
        volumes:
            - .:/v4app
        environment:
            - MONGO_URI=mongodb://mongodb-v4-prov:27017
