# local config is being used for running component locally for testing and debugging purposes

server:
  apiVersion: v1
  address: ":8443"
  static: "./tmp"

logger:
  level: debug
  addCaller: true
  outputPaths:
    - stdout
    - tmp/lyre-be.log

database:
  URI: "mongodb://localhost:27017"
  name: "v4"
  timeout: 1

docview:
  path: \\TRFILESVR01\SCANDOCTX\BOLS\JK\

sap:
  auth: "Basic amt1bGFtOm1hZGl4MTI="
  docList: "https://madixinc.apimanagement.us21.hana.ondemand.com/v1/rf/zgws_documentlist"
  docGet: "http://sapps200.madixinc.com:8000/sap/bc/zsd_rest_test/ZRFM_LAPP_GETDOC_BIN"
