# local config is being used for running component locally for testing and debugging purposes

# configuration of the API HTTP server
server:
  apiVersion: v1
  address: ":8443"

logger:
  level: debug
  addCaller: true
  outputPaths:
    - stdout
    - tmp/lyre-be.log
