# local config is being used for running component locally for testing and debugging purposes

server:
  apiVersion: v1
  address: ":8443"

logger:
  level: debug
  addCaller: true
  outputPaths:
    - stdout
    - tmp/lyre-be.log

database:
  URI: "mongodb://localhost:27017"
  name: "v4"
  timeout: 1
