# local config is being used for running component locally for testing and debugging purposes

server:
  apiVersion: v1
  address: ":443"
  JWTSecret: "BXokUG7Qwhl8795D4Ry+jIYcrCcrx"

logger:
  level: info
  addCaller: true
  outputPaths:
    - stdout
    - /opt/lyre-be/logs/lyre-be.log

database:
  URI: "mongodb://localhost:27017"
  name: "v4"
  timeout: 1
